### ISSUE TITLE
release-1.1 deployment instructions is pointing to wrong links

### ISSUE THREAD

**Issue by fidencio** [openshift/sandboxed-containers-operator#158]
**Description**

https://github.com/openshift/sandboxed-containers-operator/tree/release-1.1#without-a-git-repo-checkout points to a non-existent file.

The document mentions:
> To deploy the operator and create a custom resource (which installs Kata on all worker nodes), run curl https://raw.githubusercontent.com/openshift/sandboxed-containers-operator/master/deploy/install.sh | bash

However, https://raw.githubusercontent.com/openshift/sandboxed-containers-operator/master/deploy/install.sh is a non-existent file.
Most likely it should point to https://raw.githubusercontent.com/openshift/sandboxed-containers-operator/release-1.1/deploy/install.sh

**Steps to reproduce the issue:**
1. Open your web browser
2. Go to https://github.com/openshift/sandboxed-containers-operator/tree/release-1.1#without-a-git-repo-checkout
3. Try to follow the instructions provided

**Describe the results you received:**
```
[fidencio@kundera ocp]$ curl https://raw.githubusercontent.com/openshift/sandboxed-containers-operator/master/deploy/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0     57      0 --:--:-- --:--:-- --:--:--    57
bash: line 1: 404:: command not found
```
**Describe the results you expected:**

The deployment would start.

**Additional information you deem important (e.g. issue happens only occasionally):**

Not relevant

**Output of `oc describe kataconfig <your-kataconfig>`:**

```
Not relevant
```

**Additional environment details (platform, options, etc.):**

Not relevant

**Comment by fidencio** [comment]
Note that the script itself also has to be updated to point to the release branch.

**Comment by bpradipt** [comment]
Fixed via https://github.com/openshift/sandboxed-containers-operator/pull/160
