### ISSUE TITLE
release-1.1: deployment breaks due to `flag provided but not defined: -metrics-addr`

### ISSUE THREAD

**Issue by fidencio** [openshift/sandboxed-containers-operator#159]
**Description**

It's absolutely impossible to deploy the sandboxed-containers operator following instructions from the release-1.1 branch.
After manually editing the installation script to point to the content of the release-1.1 branch, due to https://github.com/openshift/sandboxed-containers-operator/issues/158, the deployment simply breaks due to:
```
[fidencio@kundera ~]$ oc -n openshift-sandboxed-containers-operator logs openshift-sandboxed-containers-controller-manager-7df78c78mn4fw                                             
flag provided but not defined: -metrics-addr
Usage of /manager:        
  -kubeconfig string                                                                                                                                                                 
        Paths to a kubeconfig. Only required if out-of-cluster.
  -leader-elect                                                                                                                                                                      
        Enable leader election for controller manager. Enabling this will ensure there is only one active controller manager.                                                        
  -metrics-bind-address string
```

**Steps to reproduce the issue:**
1. Open your web browser
2. Go to https://github.com/openshift/sandboxed-containers-operator/tree/release-1.1#without-a-git-repo-checkout
3. Work around https://github.com/openshift/sandboxed-containers-operator/issues/158 by:
    3.1. Manually getting https://raw.githubusercontent.com/openshift/sandboxed-containers-operator/master/deploy/install.sh
    3.2. Change references from master to release-1.1
4. Run the script
5. After some time check the state of the controller manager pod (`oc get pods -n openshift-sandboxed-containers-operator | grep controller-manager`), and verify it's in CrashLoopBackOff
6. Check its logs (

**Describe the results you received:**

```
[fidencio@kundera ~]$ oc get pods -n openshift-sandboxed-containers-operator | grep controller-manager                                                                               
openshift-sandboxed-containers-controller-manager-7df78c78mn4fw   0/1     CrashLoopBackOff   10         28m                                                                          
[fidencio@kundera ~]$ oc -n openshift-sandboxed-containers-operator logs openshift-sandboxed-containers-controller-manager-7df78c78mn4fw                                             
flag provided but not defined: -metrics-addr
Usage of /manager:        
  -kubeconfig string                                                                                                                                                                 
        Paths to a kubeconfig. Only required if out-of-cluster.
  -leader-elect                                                                                                                                                                      
        Enable leader election for controller manager. Enabling this will ensure there is only one active controller manager.                                                        
  -metrics-bind-address string
        The address the metric endpoint binds to. (default ":8080")   
```

**Describe the results you expected:**

That the installation would succeed.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `oc describe kataconfig <your-kataconfig>`:**

```
[fidencio@kundera ~]$ oc describe kataconfig example-kataconfig
Name:         example-kataconfig
Namespace:    
Labels:       <none>
Annotations:  <none>
API Version:  kataconfiguration.openshift.io/v1
Kind:         KataConfig
Metadata:
  Creation Timestamp:  2021-11-30T13:25:40Z
  Generation:          1
  Managed Fields:
    API Version:  kataconfiguration.openshift.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:kataConfigPoolSelector:
          .:
          f:matchLabels:
            .:
            f:custom-kata1:
    Manager:         kubectl-client-side-apply
    Operation:       Update
    Time:            2021-11-30T13:25:40Z
  Resource Version:  24566
  UID:               a35db2f0-eea0-43ed-b41c-2c8dc14e4292
Spec:
  Kata Config Pool Selector:
    Match Labels:
      custom-kata1:  test
Events:              <none>
```

**Additional environment details (platform, options, etc.):**

**Comment by fidencio** [comment]
Feels like cbebd561bfa0a3967db447bb051cc451e4447e65 is missing a backport, and a release.

**Comment by fidencio** [comment]
Hmm.  This may actually be related to mistakenly using a 4.8 OCP cluster, rather than a 4.9 one.

**Comment by fidencio** [comment]
Yep, that was the case, although installation via the instructions (as in cmd line) didn't work at all.
The installation via the clicky-clicky web UI did.

@bpradipt, I'll leave this one up to you to figure out whether it should be kept open or not.
Maybe checking for the OCP version before deploying the operator would be a reasonable thing to do, considering the operator version is tied to an OCP version.

**Comment by bpradipt** [comment]
@fidencio I think it's a fair point to check for OCP version in the code itself. Right now the supported OCP version is mentioned in the bundle annotation which ensures that the operator bundle gets added to the right catalog index. However this is only downstream.  May be we can use this issue to track addition of necessary checks in the operator code? wdyt?
