### ISSUE TITLE
status not updated when nodes are added/removed from machine config pool

### ISSUE THREAD

**Issue by jensfr** [openshift/sandboxed-containers-operator#170]
**Description**

the status update (installation/uninstallation) is only updated when the kataconfig CR is
created or deleted. When a custom MCP is used and a node is added or removed it is 
not updated even though it triggers enabling/disabling the sandboxed-containers extension
on nodes
 
**Steps to reproduce the issue:**
1. create a kataconfig and specify a node selector
2. add label to two nodes -> extension will be enabled on those nodes
3.  remove label from one of those nodes -> extension is disabled on this node but status doesn't reflect that operatorion 

**Describe the results you received:**

when removing a label from the node there was no update

**Describe the results you expected:**

an updated status showing that something is going on

What we could do is: 
-  cache the previous size of the mcp and when mcp status is updating and size 
     1. increase: clear install status, set installing=true, update install stats, set installing=false when mcp status is 'updated'
     2. decreased: clear uninstall status, set uninstalling=true, update uninstall stats, set uninstalling=false when mcp status is 'updated'
     3. when size is unchanged, but mcp is updating: do 1. and 2 (maybe same number of nodes was removed and added at the same time)

**Comment by pmores** [comment]
@jensfr how do we learn about what happened though? Removing a label from a node resource won't by itself trigger our reconciliation, will it? Or can we rely on OSC reconciliation being triggered on node label removal in some indirect way? Perhaps we'll need to start to watch Nodes as well.
