### ISSUE TITLE
DEVELOPMENT.md is out of date and does not work

### ISSUE THREAD

**Issue by cpmeadors** [openshift/sandboxed-containers-operator#207]
Prereqs say golang 1.16+, but 1.18 apparently doesn't work.  Also operator-sdk is up to 1.20

make build results in an error during "generate' due to missing controller-gen

/home/cmeadors/repos/github.com/openshift/sandboxed-containers-operator/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
bash: line 1: /home/cmeadors/repos/github.com/openshift/sandboxed-containers-operator/bin/controller-gen: No such file or directory
make: *** [Makefile:91: manifests] Error 127

make controll-gen succeeds but does not resolve the error.  Only manually "go getting" and copying the binary to the local bin dir resolves the issue.

Then make build fails because setup-envtest binary is not found similarly to controller-gen (make envtest does not put the binary in the local bin dir)

**Comment by cpmeadors** [comment]
Same issue with kustomize.  make kustomize does not place the binary in the local bin dir as expected.

**Comment by littlejawa** [comment]
We probably can close this:
- The pre-requisites were updated as part of upgrading the operator-sdk.
- The build instructions seems to work now.
