### ISSUE TITLE
Update to operator-sdk 1.23

### ISSUE THREAD

**Issue by cpmeadors** [openshift/sandboxed-containers-operator#213]
We are currently on operator-sdk 1.20.  Latest is 1.23.  We need to update the operator-sdk version and apply all the migration changes listed in the docs:

https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.21.0/
https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.22.0/
https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.23.0/

This will also need a golang update to 1.18.  Not sure if that can be a separate change or not, but I will file a separate issue for tracking.

**Comment by littlejawa** [comment]
Making progress on this: moved to 1.21 (#233) and 1.22 (#235).
Working on 1.23

**Comment by littlejawa** [comment]
Actually, this was fixed with #237 
Closing
