### ISSUE TITLE
OKD: Choosing the right machine config extension on FCOS

### ISSUE THREAD

**Issue by smuda** [openshift/sandboxed-containers-operator#267]
**Description**

The machine config operator handles RHCOS and FCOS differently when effectuating machine config extensions.

On RHCOS it uses a hardcoded list which is then translated into the actual packages. In our case, sandboxed-containers are translated into kata-containers and then rpm-ostree is called.

On FCOS it just pipes the extensions directly into rpm-ostree, which means that in the current implementation it tries to install sandboxed-containers which doesn't exist in FCOS yum repo.

**Steps to reproduce the issue:**
1. Install OKD.
2. Enable the fcos.repo yum repo.
3. Install sandboxed-containers and create a kataconfig

**Describe the results you received:**

On FCOS, the worker node complains about there is no rpm package sandboxed-containers.

**Describe the results you expected:**

The package kata-containers would be installed.

**Additional environment details (platform, options, etc.):**
OKD 4.12 with FCOS.

**Comment by smuda** [comment]
See PR https://github.com/openshift/sandboxed-containers-operator/pull/266

**Comment by bpradipt** [comment]
@smuda with the changes in PR #266 can sandboxed-containers be installed in an OKD cluster ?

**Comment by smuda** [comment]
Well... it's a step on the way. Running #266 enables to install kata-containers on an OKD cluster. After that I ran into #265 which seems to be a kata-container problem.
