### ISSUE TITLE
Uninstall fails due to incorrect node name when Kata is installed on selected nodes

### ISSUE THREAD

**Issue by bpradipt** [openshift/sandboxed-containers-operator#68]
**Description**

Uninstall fails when Kata is installed on selected nodes
**Steps to reproduce the issue:**
1. Create a KataConfig with kataConfigPoolSelector
2. Wait for Kata payload installation to succeed
3. Delete the KataConfig (Uninstall)

**Describe the results you received:**
```
2021-02-23T18:00:24.139Z        INFO    controllers.KataConfig  Removing the kata pool selector label from the node     {"node name ": "ip-10-0-223-105"}
2021-02-23T18:00:24.144Z        ERROR   controller      Reconciler error        {"reconcilerGroup": "kataconfiguration.openshift.io", "reconcilerKind": "KataConfig", "controller": "kataconfig", "name": "example-kataconfig", "namespace": "", "error": "nodes \"ip-10-0-223-105\" not found"}
github.com/go-logr/zapr.(*zapLogger).Error
        /go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:246
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:218
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:197
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
        /go/pkg/mod/k8s.io/apimachinery@v0.19.0/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
        /go/pkg/mod/k8s.io/apimachinery@v0.19.0/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
        /go/pkg/mod/k8s.io/apimachinery@v0.19.0/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
        /go/pkg/mod/k8s.io/apimachinery@v0.19.0/pkg/util/wait/wait.go:90
```

**Describe the results you expected:**
Successful uninstall

**Additional information you deem important (e.g. issue happens only occasionally):**
The problem happens due to a mismatch of the node name.  Kata install/uninstall is using host name and not `fqdn` as the node name. For environments like AWS the actual node name is fqdn - `ip-10-0-223-105.ec2.internal` whereas the host name returned is `ip-10-0-223-105`. 

A possible fix is to modify the following code to return fqdn - https://github.com/openshift/sandboxed-containers-operator/blob/master/images/daemon/pkg/daemon/kata_actions.go#L62

**Additional environment details (platform, options, etc.):**
OpenShift cluster in AWS

**Comment by bpradipt** [comment]
@jensfr I can take this one

**Comment by jensfr** [comment]
@bpradipt thanks for the report and working on it :-) :+1:
