### ISSUE TITLE
[RFE] Support sandboxed-containers-operator as part of OKD

### ISSUE THREAD

**Issue by fidencio** [openshift/sandboxed-containers-operator#86]
Currently, sandboxed-containers-operator only works on OpenShift.  This happens mainly due to packages we depend on that are not part of Fedora (and, consequently, not part of Fedora CoreOS).

We need to re-evaluate this as soon as we have a modular QEMU available on Fedora and we also take advantage of the modular QEMU downstream.  Plus, internally at Red Hat, we have folks evaluating the possibility / benefits of having the project as part of OKD.

This is issue is a place holder for the effort, and those interested in OKD can subscribe to this issue here.

**Comment by fidencio** [comment]
/remove-lifecycle stale

As someone from the community may end up working on this.

**Comment by fidencio** [comment]
/remove-lifecycle stale

As someone from the community may end up working on this.

**Comment by smuda** [comment]
OKD support would be a great thing! Is it only the package-names that are different?
